language: python
python:
    - "2.7"
    - "3.6"
env:
    - TORNADO_VERSION=5.0
    - TORNADO_VERSION=4.5.3
    - TORNADO_VERSION=3.2.2
install:
    - "pip install -r requirements.txt"
    - "pip install tornado==$TORNADO_VERSION"
    - "pip install 'pytest<4.0'"
    - "pip install 'pytest-cov<=2.6'"
    - "pip install coverage"
    - "pip install coveralls"
    - "pip install mock"
script:
    coverage run --source=tornado_json setup.py test
after_success:
    coveralls --verbose
